services:
  - type: web
    name: paddleocr-api
    env: python
    plan: free
    region: singapore
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=1 --threads=4 --timeout=120 --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: WEB_CONCURRENCY
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
